image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apk add --update python-dev
    - cd termCounterServer
    - python -m unittest test_suite
    - cd ..
    - echo Tests finished.

step-deploy-prod:
  stage: deploy
  script:
    - apk add --update py-pip
    - pip install docker-compose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
    - echo Deploy finished.